### ISSUE TITLE
Create Android App

### ISSUE THREAD

**Issue by AchoArnold** [NdoleStudio/hepilo#1]
Create android app and submit to play store.

**Comment by AchoArnold** [comment]
App Created https://play.google.com/store/apps/details?id=com.hepilo.twa

**Comment by Poussinou** [comment]
Hi,

Would it be possible to tag your [releases](https://github.com/NdoleStudio/hepilo/releases) and attach a signed release APK to it, so that people without Play Store can still download and use your app?

Thanks

**Comment by AchoArnold** [comment]
Hey @Poussinou,

I'll do that. See https://github.com/NdoleStudio/hepilo/issues/4
