### ISSUE TITLE
Login required?

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [NdoleStudio/hepilo#145]
I'm running the APK on my android and it's asking me to login using Google or an email - what gives?

Why can't this just be a locally-run app without needing a login?  I don't need this to sync or anything... I just want a simple app to keep a list.

Also, opening the app gives me what looks like the project webpage where it tells me I can get the app on Google Play... makes absolutely no sense.

**Comment by AchoArnold** [comment]
Hello  @PlebeiusGaragicus,

> Why can't this just be a locally-run app without needing a login? I don't need this to sync or anything... I just want a simple app to keep a list.

You can use the `Demo` which doesn't require you to login but it won't store your list in the cloud. I use the login feature for people who want to sync.

> Also, opening the app gives me what looks like the project webpage where it tells me I can get the app on Google Play... makes absolutely no sense.

I think it's the "landing" page, it tells you what the app is about and you will see a button there to login or to try the demo. I will remove the play store button from the app when you open it for the first time so it's not confusing.
