### ISSUE TITLE
(Mobile) Browser bar is still shown in Firefox

### ISSUE THREAD

**Issue by ghost** [NdoleStudio/hepilo#3]
When Chrome is set as the default browser, the browser bar is hidden.
When Firefox (and probably other browsers that aren't based on Chromium) is set as the default browser, the browser bar is still visible.

**Comment by AchoArnold** [comment]
Hello @logicalwillow 

Do you mean the android app. Or the website? I tried it on my Firefox browser and it looks ok as a browser and as standalone

Anyway to reduce?
![Screenshot_20220805-214034](https://user-images.githubusercontent.com/4196457/183141115-6c6739c0-33fa-4a2f-9d73-73965ca6a808.png)
![Screenshot_20220805-213551](https://user-images.githubusercontent.com/4196457/183141120-d11cf55e-95c1-44bc-8421-b7da76010987.png)

**Comment by ghost** [comment]
I meant the Android app. This is what it looks like for me:
![Screenshot_20220806-072955_Firefox](https://user-images.githubusercontent.com/56515875/183249021-a904ced2-827b-46c9-ba27-1eefe6d6358d.png)

**Comment by AchoArnold** [comment]
Hello @logicalwillow 
I can't reproduce this, unfortunately. Which android phone are you using? Perhaps it will make more sense to just install the PWA from the website https://hepilo.com?
