### ISSUE TITLE
Create Signed android App in release

### ISSUE THREAD

**Issue by AchoArnold** [NdoleStudio/hepilo#4]

**Comment by Poussinou** [comment]
Hi,

Some links about tagging a release [here](https://help.github.com/articles/creating-releases/) and [here](https://blog.github.com/2013-07-02-release-your-software/).

**Comment by AchoArnold** [comment]
I created a release with the mobile app @Poussinou  https://github.com/NdoleStudio/hepilo/releases/tag/v0.0.1
